# Generated by Django 2.2.18 on 2021-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用例编号')),
                ('product', models.CharField(max_length=100, verbose_name='所属产品')),
                ('case_module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('relate_requirement', models.CharField(max_length=10000, verbose_name='相关需求')),
                ('case_title', models.TextField(max_length=100, verbose_name='用例标题')),
                ('Preconditions', models.TextField(max_length=100, verbose_name='前置条件')),
                ('step', models.TextField(max_length=10000, verbose_name='步骤')),
                ('Expected', models.TextField(max_length=100, verbose_name='预期')),
                ('actual_situation', models.TextField(max_length=10000, verbose_name='实际情况')),
                ('key_word', models.CharField(max_length=100, null=True, verbose_name='关键词')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('case_type', models.CharField(max_length=100, verbose_name='用例类型')),
                ('Applicable_stage', models.CharField(max_length=100, null=True, verbose_name='适用阶段')),
                ('case_status', models.CharField(max_length=100, verbose_name='用例状态')),
                ('bug_num', models.IntegerField(verbose_name='B')),
                ('result_num', models.IntegerField(verbose_name='R')),
                ('step_num', models.IntegerField(verbose_name='S')),
                ('result', models.CharField(max_length=100, null=True, verbose_name='结果')),
                ('creater', models.CharField(default=None, max_length=100, verbose_name='由谁创建')),
                ('create_date', models.CharField(default='', max_length=100, null=True, verbose_name='创建日期')),
                ('Last_Modified', models.CharField(max_length=100, verbose_name='最后修改者')),
                ('Modified_date', models.CharField(default='', max_length=100, null=True, verbose_name='修改日期')),
                ('case_version', models.CharField(default='', max_length=10, verbose_name='用例版本')),
                ('relate_case', models.CharField(blank=True, max_length=100, null=True, verbose_name='相关用例')),
            ],
        ),
        migrations.CreateModel(
            name='GitCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.TextField(max_length=100, verbose_name='用例标题')),
                ('case_type', models.CharField(max_length=100, null=True, verbose_name='用例类型')),
                ('case_module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('priority', models.IntegerField(null=True, verbose_name='优先级')),
                ('run_env', models.CharField(max_length=100, verbose_name='运行环境')),
                ('test_type', models.CharField(max_length=100, verbose_name='测试类型')),
                ('owner', models.CharField(max_length=100, null=True, verbose_name='所属人')),
                ('Last_Modified', models.CharField(max_length=100, verbose_name='最后修改者')),
                ('Modified_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default=None, max_length=100, verbose_name='计划名称')),
                ('run_env', models.CharField(choices=[('1', '网关'), ('2', '隔离')], default=('1', '网关'), max_length=100, verbose_name='运行环境')),
                ('case_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='用例条数')),
                ('pass_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='成功条数')),
                ('fail_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='失败条数')),
                ('case_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='用例id列表')),
                ('pass_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='成功id列表')),
                ('fail_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='失败id列表')),
                ('time', models.CharField(blank=True, default='', max_length=100, null=None, verbose_name='耗时')),
                ('purpose', models.CharField(choices=[('1', '冒烟测试'), ('2', '回归bug'), ('3', '回归版本'), ('4', '出厂测试'), ('5', '功能测试'), ('6', '性能测试'), ('7', '稳定性测试')], default=('1', '冒烟测试'), max_length=100, verbose_name='测试目的')),
                ('executor', models.CharField(blank=True, max_length=32, verbose_name='执行者')),
                ('analyst', models.CharField(blank=True, max_length=32, verbose_name='分析者')),
                ('label', models.CharField(blank=True, max_length=32, verbose_name='标签')),
                ('result_type', models.CharField(choices=[('1', '版本问题'), ('2', '环境问题'), ('3', '脚本问题')], default=('1', '版本问题'), max_length=32, verbose_name='结果类型')),
                ('analysis_result', models.TextField(blank=True, verbose_name='分析结果')),
                ('cycle_num', models.IntegerField(blank=True, default=0, verbose_name='循环次数')),
                ('component_version', models.CharField(blank=True, max_length=32, verbose_name='组件版本')),
                ('last_run', models.CharField(blank=True, default='', max_length=100, verbose_name='最后一次运行时间')),
                ('last_plan', models.CharField(blank=True, default='', max_length=100, verbose_name='下次计划')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default=None, max_length=100, verbose_name='计划名称')),
                ('run_env', models.CharField(default=None, max_length=100, verbose_name='运行环境')),
                ('case_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='用例条数')),
                ('pass_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='成功条数')),
                ('fail_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='失败条数')),
                ('case_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='用例id列表')),
                ('pass_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='成功id列表')),
                ('fail_list', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='失败id列表')),
                ('time', models.CharField(blank=True, default='', max_length=100, null=None, verbose_name='耗时')),
                ('purpose', models.CharField(default=None, max_length=100, verbose_name='测试目的')),
                ('executor', models.CharField(blank=True, max_length=32, verbose_name='执行者')),
                ('analyst', models.CharField(blank=True, max_length=32, verbose_name='分析者')),
                ('label', models.CharField(blank=True, max_length=32, verbose_name='标签')),
                ('result_type', models.CharField(default=None, max_length=32, verbose_name='结果类型')),
                ('analysis_result', models.TextField(blank=True, verbose_name='分析结果')),
                ('cycle_num', models.IntegerField(blank=True, default=0, verbose_name='循环次数')),
                ('component_version', models.CharField(blank=True, max_length=32, verbose_name='组件版本')),
                ('last_run', models.CharField(blank=True, default='', max_length=100, verbose_name='最后一次运行时间')),
                ('last_plan', models.CharField(blank=True, default='', max_length=100, verbose_name='下次计划')),
                ('report_path', models.CharField(blank=True, default='', max_length=100, verbose_name='报告路径')),
                ('plan_id', models.CharField(blank=True, default='', max_length=10, verbose_name='计划id')),
            ],
        ),
    ]
